//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.OwnedCard = new HashSet<OwnedCard>();
        }
    
        public long id { get; set; }
        public long fk_base_id { get; set; }
        public long fk_language_id { get; set; }
        public string artwork { get; set; }
        public Nullable<long> fk_artist_id { get; set; }
        public Nullable<long> fk_rarity_id { get; set; }
        public Nullable<long> fk_set_id { get; set; }
        public string flavor_text { get; set; }
        public Nullable<long> number { get; set; }
        public string version { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Set Set { get; set; }
        public virtual Rarity Rarity { get; set; }
        public virtual Language Language { get; set; }
        public virtual CardBase CardBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnedCard> OwnedCard { get; set; }
    }
}
