//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardBase()
        {
            this.Card = new HashSet<Card>();
            this.CardSubtype = new HashSet<CardSubtype>();
            this.CardType = new HashSet<CardType>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public long power { get; set; }
        public long toughness { get; set; }
        public string mana_cost { get; set; }
        public Nullable<long> cmc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardSubtype> CardSubtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardType> CardType { get; set; }
    }
}
