//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGCM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Block> Block { get; set; }
        public virtual DbSet<CardBase> CardBase { get; set; }
        public virtual DbSet<CardSubtype> CardSubtype { get; set; }
        public virtual DbSet<CardType> CardType { get; set; }
        public virtual DbSet<Deck> Deck { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<OwnedCard> OwnedCard { get; set; }
        public virtual DbSet<Rarity> Rarity { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<SetType> SetType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
