//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnedCard
    {
        public long id { get; set; }
        public long fk_card_id { get; set; }
        public Nullable<long> fk_user_id { get; set; }
        public Nullable<long> fk_deck_id { get; set; }
        public Nullable<bool> foil { get; set; }
        public Nullable<bool> signed { get; set; }
        public Nullable<long> condition { get; set; }
        public Nullable<bool> altered { get; set; }
        public string tags { get; set; }
        public string comment { get; set; }
    
        public virtual CardBase CardBase { get; set; }
        public virtual Deck Deck { get; set; }
        public virtual User User { get; set; }
    }
}
