//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Set()
        {
            this.CardBase = new HashSet<CardBase>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string abbrev { get; set; }
        public string symbol { get; set; }
        public Nullable<System.DateTime> relase_date { get; set; }
        public Nullable<long> fk_block_id { get; set; }
        public Nullable<long> cards_total { get; set; }
        public Nullable<long> fk_type_id { get; set; }
    
        public virtual Block Block { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardBase> CardBase { get; set; }
        public virtual SetType SetType { get; set; }
    }
}
